// react-sliderpuzzle/src/components/Puzzle/PuzzleBoard.tsx
import React, {
	useState,
	useEffect,
	useRef,
	forwardRef,
	useImperativeHandle,
} from "react";

import PuzzleTile from "./PuzzleTile";

import { useRandomImage } from "queries/image.queries";

import type {
	TileProps,
	PuzzleBoardProps,
} from "utils/types/puzzleboard.types";

import MonkImage from "assets/monks.jpg";
import "./PuzzleBoard.scss";

export interface PuzzleBoardRef {
	createPuzzle: (args: PuzzleBoardProps) => void;
}

const PuzzleBoard = forwardRef<PuzzleBoardRef, PuzzleBoardProps>(
	({ image, size }, ref) => {
		const [tiles, setTiles] = useState<TileProps[]>([]);
		const [tileSize, setTileSize] = useState({ width: 0, height: 0 });
		const [isSolved, setIsSolved] = useState(false);

		const frameRef = useRef<HTMLDivElement>(null);

		const { data: randomImage, refetch: getRandomImage } = useRandomImage();

		useImperativeHandle(ref, () => ({
			createPuzzle,
		}));

		useEffect(() => {
			createPuzzle({ image, size });
		}, [image, size]);

		const createPuzzle = ({ image, size }: PuzzleBoardProps) => {
			const img = new Image();

			img.onload = () => {
				const tileWidth = Math.floor(img.width / size.horizontal);
				const tileHeight = Math.floor(img.height / size.vertical);

				setTileSize({ width: tileWidth, height: tileHeight });
				generateTiles(tileWidth, tileHeight);
			};
			img.src = image?.urls?.small;
		};

		const generateTiles = (tileWidth: number, tileHeight: number) => {
			console.log(image?.urls?.small);
			const newTiles = Array.from(
				{ length: size.horizontal * size.vertical },
				(_, i) => ({
					styles: {
						background: i === 0 ? "transparent" : `url(${image?.urls?.small})`,
						backgroundPositionX: `-${(i % size.horizontal) * tileWidth}px`,
						backgroundPositionY: `-${
							Math.floor(i / size.horizontal) * tileHeight
						}px`,
						width: `${tileWidth}px`,
						height: `${tileHeight}px`,
						order: i,
					},
					position: i,
					isEmpty: i === 0,
				})
			);

			setTiles(newTiles);
			shuffleTiles(newTiles);
		};

		const shuffleTiles = (tiles: TileProps[]) => {
			const shuffledTiles = [...tiles];

			for (let i = 0; i < shuffledTiles.length * 5; i++) {
				const emptyTile = shuffledTiles.find((t) => t?.isEmpty);
				const adjacentTiles = getAdjacentTiles(emptyTile!, shuffledTiles);
				const randomTile =
					adjacentTiles[Math.floor(Math.random() * adjacentTiles.length)];
				switchTiles(emptyTile!, randomTile);
			}
			setTiles(shuffledTiles);
		};

		const moveTile = (tile: TileProps) => {
			const emptyTile = tiles.find((t) => t?.isEmpty);
			if (emptyTile && getAdjacentTiles(tile, tiles).includes(emptyTile)) {
				const updatedTiles = [...tiles];
				switchTiles(emptyTile, tile);
				setTiles(updatedTiles);
				checkIfSolved(updatedTiles);
			}
		};

		const switchTiles = (tileA: TileProps, tileB: TileProps) => {
			[tileA.styles.order, tileB.styles.order] = [
				tileB.styles.order,
				tileA.styles.order,
			];
		};

		const getAdjacentTiles = (tile: TileProps, tiles: TileProps[]) => {
			const pos = tile.styles.order;
			return tiles.filter((t) =>
				[
					pos % size.horizontal ? pos - 1 : null,
					(pos + 1) % size.horizontal ? pos + 1 : null,
					pos - size.horizontal,
					pos + size.horizontal,
				].includes(t.styles.order)
			);
		};

		const checkIfSolved = (tiles: TileProps[]) => {
			setIsSolved(tiles.every((tile) => tile.styles.order === tile.position));
		};

		const onRestart = async () => {
			try {
				await getRandomImage();

				if (randomImage) {
					createPuzzle({
						image: randomImage,
						size,
					});
				} else {
					throw new Error("No image found");
				}
			} catch (error) {
				console.error("Failed to get random image:", error);
				createPuzzle({ image: MonkImage, size });
			}
		};

		return (
			<main className="board">
				<div className="puzzle-board">
					<div
						className="frame-wrapper"
						ref={frameRef}
						style={{
							width: `${tileSize.width * size.horizontal}px`,
							height: `${tileSize.height * size.vertical}px`,
						}}
					>
						{isSolved && <h2 className="win">You Win!</h2>}

						<div className="frame">
							{tiles.map((tile) => (
								<PuzzleTile key={tile.position} tile={tile} onMove={moveTile} />
							))}
						</div>
					</div>

					<div className="preview">
						<h3>Image Preview</h3>
						<img src={image?.urls?.small} alt={image?.alt_description} />
					</div>
				</div>

				<div className="controls">
					<button
						type="button"
						className="shuffle"
						onClick={() => shuffleTiles(tiles)}
					>
						Reshuffle Puzzle
					</button>

					<button type="button" className="restart" onClick={onRestart}>
						New Game
					</button>
				</div>
			</main>
		);
	}
);

export default PuzzleBoard;

// vue-sliderpuzzle/src/components/Puzzle/PuzzleBoard.vue
<template>
  <main class="board">
    <!-- Puzzle Board -->
    <div class="puzzle-board">
      <div class="frame-wrapper" :style="frameSize">
        <h2 v-if="isSolved" class="win">You Win!</h2>

        <div class="frame" :style="frameSize">
          <PuzzleTile v-for="tile in tiles" :key="tile.position" :tile="tile" @move="moveTile" />
        </div>
      </div>

      <!-- Image Preview -->
      <div class="preview">
        <h3>Image Preview</h3>
        <img v-if="image" :src="image" :alt="imageAlt" />
      </div>
    </div>

    <!-- Controls -->
    <div class="controls">
      <button type="button" class="shuffle" @click="shuffleTiles">Reshuffle Puzzle</button>
      <button type="button" class="restart" @click="restartGame">New Game</button>
    </div>
  </main>
</template>

<script lang="ts">
import { ref, computed } from 'vue'
import { sample } from 'lodash'
import { storeToRefs } from 'pinia'

import PuzzleTile from './PuzzleTile.vue'

import { useImageStore } from '@/stores/imageStore'

import monksImage from '@/assets/monks.jpg'

export default {
  components: { PuzzleTile },

  setup() {
    const image = ref('')
    const imageAlt = ref('')
    const size = ref({ horizontal: 4, vertical: 4 })
    const tiles = ref<
      {
        styles: {
          background: string
          backgroundPositionX: string
          backgroundPositionY: string
          width: string
          height: string
          order: number
        }
        position: number
        isEmpty: boolean
      }[]
    >([])
    const tileSize = ref({ width: 0, height: 0 })

    const imageStore = useImageStore()
    const { randomImage } = storeToRefs(imageStore)
    const { getRandomImage } = imageStore

    // Frame size calculation
    const frameSize = computed(() => ({
      width: `${tileSize.value.width * size.value.horizontal}px`,
      height: `${tileSize.value.height * size.value.vertical}px`,
    }))

    // Check if the puzzle is solved
    const isSolved = computed(() => {
      return tiles.value.every((tile) => tile.styles.order === tile.position)
    })

    // Create a new puzzle
    function createPuzzle({
      image: img,
      size: newSize,
    }: {
      image: { urls: { small: string }; alt_description: string }
      size: { horizontal: number; vertical: number }
    }) {
      console.log(img)
      image.value = (img?.urls.small || monksImage) as string
      imageAlt.value = img?.alt_description || 'Default image'
      size.value = newSize

      const imgElement = new Image()
      imgElement.onload = () => {
        tileSize.value.width = Math.floor(imgElement.width / size.value.horizontal)
        tileSize.value.height = Math.floor(imgElement.height / size.value.vertical)
        generatePuzzleTiles()
        shuffleTiles()
      }
      imgElement.src = image.value as unknown as string
    }

    // Generate puzzle tiles
    function generatePuzzleTiles() {
      tiles.value = Array.from({ length: size.value.horizontal * size.value.vertical }, (_, i) => ({
        styles: {
          background: i === 0 ? 'transparent' : `url(${image.value})`,
          backgroundPositionX: `-${(i % size.value.horizontal) * tileSize.value.width}px`,
          backgroundPositionY: `-${Math.floor(i / size.value.horizontal) * tileSize.value.height}px`,
          width: `${tileSize.value.width}px`,
          height: `${tileSize.value.height}px`,
          order: i,
        },
        position: i,
        isEmpty: i === 0,
      }))
    }

    // Shuffle tiles
    function shuffleTiles() {
      for (let i = 0; i < tiles.value.length * 5; i++) {
        const emptyTile = tiles.value.find((t) => t.isEmpty)
        const movableTiles = tiles.value.filter((t) =>
          getAdjacentOrders(emptyTile).includes(t.styles.order),
        )

        switchTiles(emptyTile, sample(movableTiles))
      }
    }

    // Move a tile
    function moveTile(tile: {
      styles: {
        background: string
        backgroundPositionX: string
        backgroundPositionY: string
        width: string
        height: string
        order: number
      }
      position: number
      isEmpty: boolean
    }) {
      if (tile.isEmpty) return
      const targetTile = tiles.value.find(
        (t) => t.isEmpty && getAdjacentOrders(tile).includes(t.styles.order),
      )
      if (targetTile) switchTiles(targetTile, tile)
    }

    // Switch two tiles
    function switchTiles(
      tileA:
        | {
            styles: {
              background: string
              backgroundPositionX: string
              backgroundPositionY: string
              width: string
              height: string
              order: number
            }
            position: number
            isEmpty: boolean
          }
        | undefined,
      tileB:
        | {
            styles: {
              background: string
              backgroundPositionX: string
              backgroundPositionY: string
              width: string
              height: string
              order: number
            }
            position: number
            isEmpty: boolean
          }
        | undefined,
    ) {
      if (tileA && tileB) {
        ;[tileA.styles.order, tileB.styles.order] = [tileB.styles.order, tileA.styles.order]
      }
    }

    // Get adjacent tile positions
    function getAdjacentOrders(
      tile:
        | {
            styles: {
              background: string
              backgroundPositionX: string
              backgroundPositionY: string
              width: string
              height: string
              order: number
            }
            position: number
            isEmpty: boolean
          }
        | undefined,
    ) {
      if (!tile) return []
      const pos = tile.styles.order
      return [
        pos % size.value.horizontal ? pos - 1 : null,
        (pos + 1) % size.value.horizontal ? pos + 1 : null,
        pos - size.value.horizontal,
        pos + size.value.horizontal,
      ].filter(Boolean)
    }

    // Restart the game
    function restartGame() {
      getRandomImage()

      createPuzzle({
        image: {
          urls: { small: randomImage.value?.urls.small || '' },
          alt_description: randomImage.value?.alt_description || 'Default description',
        },
        size: size.value,
      })
    }

    return {
      image,
      imageAlt,
      tiles,
      frameSize,
      isSolved,
      createPuzzle,
      shuffleTiles,
      moveTile,
      restartGame,
    }
  },
}
</script>

<style lang="scss">
.puzzle-board {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: center;
  align-items: flex-end;
  gap: 25px;
}

.frame-wrapper {
  margin-right: 50px;
  position: relative;
  box-shadow: 0 0 0px 10px;

  .original {
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
    width: 100%;
  }

  h2.win {
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    background: rgba(0, 0, 0, 0.5);
    color: $white;
    font-size: 40px;
    margin: 0 0;
    background: rgba(97, 155, 138, 0.7);
    text-transform: uppercase;
  }
}

.frame {
  display: flex;
  flex-wrap: wrap;
}

.preview {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 15px;

  img {
    max-width: 100%;
    height: auto;
  }
}

.controls {
  margin-top: 30px;

  .restart {
    background: $lite-green;
    display: inline-block;
    text-decoration: none;
    padding: 12px 12px;
    color: #000;
    border-radius: 3px;
  }

  .shuffle {
    background: $orange;
    display: inline-block;
    text-decoration: none;
    padding: 12px 12px;
    color: #000;
    border-radius: 3px;
    margin-right: 15px;
  }
}
</style>
